### ISSUE TITLE
When using two LYWSD03MMC sensors 

### ISSUE THREAD

**Issue by chani2001** [AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA#1]
I use two LYWSD03MMCs.
One sensor works well, how can I use another?

**Comment by tuccler** [comment]
I'm using three LYWSD03MMCs. Is it possible to edit the LYWSD03MMC.py so that it can handle multiple devices from blemqtt.sh? For now my workaround is to use copy the files not directly  to /home/pi but to /home/pi/senor1, /home/pi/sensor2. /home/pi/sensor3, edit them and making 3 services.

**Comment by AnthonyKNorman** [comment]
I suspect the right way to do this is to amend LYWSD03MMC.py to allow the use of multiple addresses. I will have to order another unit to work on this.

**Comment by fredddvargas** [comment]
> I'm using three LYWSD03MMCs. Is it possible to edit the LYWSD03MMC.py so that it can handle multiple devices from blemqtt.sh? For now my workaround is to use copy the files not directly to /home/pi but to /home/pi/senor1, /home/pi/sensor2. /home/pi/sensor3, edit them and making 3 services.

This wont work correctly as sometimes the connection with BLE is made with one device and cannot ask for another..

**Comment by AnthonyKNorman** [comment]
I have ordered another unit. When/if it gets here from China I will address this.

**Comment by tuccler** [comment]
@fredddvargas I also editet the MQTT Topic in LYWSD03MMC.py. So there are no devices with the same MQTT Topic. Since Monday everything is working fine and there were no connection loses. 

I'm also trying to make it work in 1 instance of the script but this could take some time.

**Comment by AnthonyKNorman** [comment]
I have updated the scripts to support this. The Pi will now connect to each sensor in turn, disconnect and move onto the next one. I have tested with two, but it can expand ad infinitum

**Comment by fredddvargas** [comment]
That sounds great @AnthonyKNorman ! thanks one more time!
