### ISSUE TITLE
Adding the MQTT host and the topic as arguments of LYWSD03MMC.py 

### ISSUE THREAD

**Issue by BlueMorph** [AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA#10]
Hi @AnthonyKNorman ,

what do you think about the idea to add the arguments

- `--mqtt-host ip-address`
- `--mqtt-topic topic-base`

to the LYWSD03MMC.py script. So your mqtt-adapted sourcecode must don't be changed by every user who wants to use your adapted script.

**Comment by AnthonyKNorman** [comment]
I like the idea for the address of the server. There should be no need to change the topic as it is now auto-generated from the MAC address of the device. Should probably add the username and password for the MQTT where folks are using authentication.

**Comment by AnthonyKNorman** [comment]
The new version of the script accepts the mqtt server as a parameter. There have been several changes. Please see the new version of Read.me.
