### ISSUE TITLE
LYWSD03MMC.py: command not found

### ISSUE THREAD

**Issue by millie75** [AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA#12]
Hi

I have a brand new install of raspbian on the Pi Zero w and have followed all the instructions and get the below when running 

LYWSD03MMC.py -d 'MAC ADDRESS'  -r -b 5 -c 1 -m 'MQTT IP' -del 20

-bash: LYWSD03MMC.py: command not found

I have copied all the files as note in the readme to /home/pi

![image](https://user-images.githubusercontent.com/51971269/77579854-e442ec00-6ed2-11ea-8595-63bb48ad9aee.png)

What am I doing wrong

**Comment by millie75** [comment]
> Hi
> 
> I have a brand new install of raspbian on the Pi Zero w and have followed all the instructions and get the below when running
> 
> LYWSD03MMC.py -d 'MAC ADDRESS' -r -b 5 -c 1 -m 'MQTT IP' -del 20
> 
> -bash: LYWSD03MMC.py: command not found
> 
> I have copied all the files as note in the readme to /home/pi
> 
> ![image](https://user-images.githubusercontent.com/51971269/77579854-e442ec00-6ed2-11ea-8595-63bb48ad9aee.png)
> 
> What am I doing wrong

I ran  chmod u+x LYWSD03MMC.py 

then ran again and got the below

from: can't read /var/mail/bluepy
./LYWSD03MMC.py: line 7: import: command not found
./LYWSD03MMC.py: line 8: import: command not found
./LYWSD03MMC.py: line 9: import: command not found
from: can't read /var/mail/dataclasses
from: can't read /var/mail/collections
./LYWSD03MMC.py: line 12: import: command not found
./LYWSD03MMC.py: line 13: import: command not found
./LYWSD03MMC.py: line 14: import: command not found
./LYWSD03MMC.py: line 15: import: command not found
./LYWSD03MMC.py: line 16: import: command not found
./LYWSD03MMC.py: line 17: import: command not found
./LYWSD03MMC.py: line 19: try:: command not found
./LYWSD03MMC.py: line 20: import: command not found
./LYWSD03MMC.py: line 21: except:: command not found
./LYWSD03MMC.py: line 22: syntax error near unexpected token `'You do not have mqtt installed, which is needed to talk to the broker.''
./LYWSD03MMC.py: line 22: `    print('You do not have mqtt installed, which is needed to talk to the broker.')'

I thought you could use a different MQTT broker on a different device, whereas these messages seem to say you need it installed on the same device.

Thanks

**Comment by AnthonyKNorman** [comment]
Hi @millie75  you can, and should, run your broker on a different device. What you don't have installed is the mqtt **_client_**. You need to run ```sudo pip3 install paho-mqtt```. 
You also need to make sure you have the full path in front of LYWSD03MMC.py as per the readme
```/home/pi/LYWSD03MMC.py -d a4:c1:38:cf:bc:2f,a4:c1:38:47:63:36 -r -b 5 -c 1 -m 192.168.0.99 -del 20```.
Can you try these changes and let me know how you get on?

**Comment by millie75** [comment]
Thanks @AnthonyKNorman , that worked absolutely fine - very impressed.
Thanks for all your hard work on this must addons :-)

**Comment by AnthonyKNorman** [comment]
Closed
