### ISSUE TITLE
How to configure hassio mqtt anonymous

### ISSUE THREAD

**Issue by antoweb** [AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA#2]
Hello,
This script send sensor data via mqtt as anonymous? If yes how to configure broker on hassio. Because from another machine i successfully send message to hassio broker with login and pwd bit this script need anonymous user?

**Comment by antoweb** [comment]
So, i solved my problem with this 2 change to file LYWSD03MMC.py :

Add line:
auth = {'username':"YOURMQTTUSERNAME", 'password':"YOURMQTTUSERPASSWORD"}

Modify line 190:

from
publish.single(topic, message, hostname=hostname)

to

publish.single(topic, message, hostname=hostname,auth=auth)

Now works good with hassio and authenticated user mqtt

**Comment by AnthonyKNorman** [comment]
Thanks for sharing this.

**Comment by fredddvargas** [comment]
Thanks!
