### ISSUE TITLE
can we change the report time?

### ISSUE THREAD

**Issue by fredddvargas** [AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA#6]
Now I think it send a mqtt message every 5 seconds, how can I change this to we not so often?

thanks in advance

**Comment by AnthonyKNorman** [comment]
I have just updated the scripts. You can now add a delay time in blemqtt.sh In my example it is 60 seconds.

**Comment by fredddvargas** [comment]
great! I will try as soon as possible! thanks!
