### ISSUE TITLE
bash wrapper to execute python script

### ISSUE THREAD

**Issue by fredddvargas** [AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA#7]
Hi @AnthonyKNorman , 

what is the idea of using a bash "wrapper" (blemqtt.sh) to then execute the python script (LYWSD03MMC.py) ?

couldnt the service directly just execute the python script LYWSD03MMC.py instead of a launching a bash script that then executes the python script?

Thanks for advance and take care!

**Comment by AnthonyKNorman** [comment]
The bash wrapper is necessary to run the loop. The script is called multiple times for different addresses and the delay prevents excessive connection. My original maintained a continuous connection. My battery didn't last very long!
