### ISSUE TITLE
Update to new (power-saving) version of LYWSD03MMC.py 

### ISSUE THREAD

**Issue by BlueMorph** [AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA#8]
Hi @AnthonyKNorman 

the original python script you used was update by @JsBergbau at his repo (see last tagged version V1.5 https://github.com/JsBergbau/MiTemperature2/tree/v1.5)

Let's integrate the power-saving changing into your adapted script. ;-) I've integrate the changes already in my forked repo. See #9

**Comment by AnthonyKNorman** [comment]
I am working on anew method for multiple devices. I will add power-saving also. Less of an issue now since I woon't be connected to the device full time.

**Comment by AnthonyKNorman** [comment]
The latest version now includes the power-saving method.
